name: "gha-test"
description: ""
runs:
  using: "composite"
  steps:
    - run: |
        python -m venv venv
        source venv/bin/activate
        pip install boto3
      shell: bash
      
    - run: echo ${{ github.action_path }}
      shell: bash
