name: Release trigger workflow

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  #pull-requests: write

jobs:
  release:
    if: github.event.issue.pull_request && (github.ref_name == 'main') && !github.event.issue.closed_at && (github.event.comment.body == '/release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'merge'
            })
