name: Release workflow

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - id: major-tag
        run: echo "tag=${GITHUB_REF_NAME%%.*}" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: Create the new tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{ steps.major-tag.outputs.tag }}`,
              sha: context.sha,
              force: true
            })
