name: Release trigger workflow

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

concurrency:  # Cancel previous builds if they are still running
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: github.event.issue.pull_request && (github.ref_name == 'main') && !github.event.issue.closed_at && (github.event.comment.body == '\release')
    runs-on: ubuntu-latest
    steps:
      - run: echo "hahaa"
