name: Release trigger workflow

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  id-token: write
  pull-requests: read

concurrency:  # Cancel previous builds if they are still running
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJson(github) }}
