name: GitHub Actions Demo

on: push

env:
  SECRETS: ${{ toJSON(secrets) }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ env.SECRETS }}' | jq -r 'to_entries[] | "\(.key) \(.value)"' |
          while read -r key value; do
            val=$(eval "echo \"$value\"")
            echo "SECRETS_${key}=$val" >> "$GITHUB_ENV"
          done
      - run: |
          import os
          for c in (os.getenv("SECRETS_TEST")):
            print(c)
        shell: python
      - run: |
          import os
          for c in (os.getenv("SECRETS_TEST_LAGI")):
            print(c)
        shell: python

