name: GitHub Actions Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            static:
              
      - if: ${{ steps.filter.outputs.static == 'true'}}
        run: echo "haha"
