name: GitHub Actions Demo

on: push

env:
  TARGET_BRANCH: ${{ github.event.release.target_commitish }}
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::error ::Target branch ($TARGET_BRANCH) is not default branch ($DEFAULT_BRANCH)."
          exit 1
