name: GitHub Actions Demo

on: push

env:
  SKIPPED_BRANCHES: '["prd", "stg", "sandbox", "main"]'

jobs:
  gha-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TRUE"
        if: ${{ contains(fromJSON(env.SKIPPED_BRANCHES), github.ref_name)}}
      - run: echo "FALSE"
        if: ${{ !contains(fromJSON(env.SKIPPED_BRANCHES), github.ref_name)}}
