name: GitHub Actions Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [one]
        exclude:
          - a: one
    steps:
      - uses: actions/checkout@v3
      - run: echo "HAHAHA"
