name: GitHub Actions Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      input: |
        {
          "TEST": "$(echo test)",
          "HAHA": "$(echo haha)"
        }
    outputs:
      output: ${{ steps.step.outputs.output }}
    steps:
      - id: step
        run: |
          OUTPUT="{}"
          echo '${{ env.input }}' | jq -r 'to_entries[] | "\(.key) \(.value)"' |
          while read -r key value; do
            val=$(eval "echo \"$value\"")
            OUTPUT=`echo $OUTPUT | jq -c --arg key "$key" --arg val "$val" '. + {($key): $val}'`
            echo "output=$OUTPUT" >> $GITHUB_OUTPUT
          done

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "${{ needs.job1.outputs.output }}"
    
