name: GitHub Actions Demo

on: push

env:
  TARGET_BRANCH: ${{ github.event.release.target_commitish }}
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Target branch (${{ env.TARGET_BRANCH }}) is not default branch (${{ env.DEFAULT_BRANCH }}).')
