name: GitHub Actions Demo

on: 
  push:
    branches:
      - main

jobs:
  test:
    name: Calver release
    runs-on: ubuntu-latest
    steps:
      - name: Exit with error
        run: |
          echo "Erroring"
          exit 1

      - name: Output report 1
        if: true
        run: |
          echo "Report 1"

      - name: Output report 2
        if: always() && true
        run: |
          echo "Report 2"

      - name: Output report 3
        if: always() && false
        run: |
          echo "Report 3"
