name: GitHub Actions Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      a: ${{ fromJSON('[]') }}
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ toJSON(env.a) == '[]' }}
