name: GitHub Actions Demo

on: push

jobs:
  job1:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1"
  
  job2:
    needs: job1
    if: always() && false
    runs-on: ubuntu-latest
    steps:
      - run: echo "job2"
