name: GitHub Actions Demo

on: push

env:
  TARGET_BRANCH: |
    {
      "TEST_ENV": "hehehe",
      "TEST_ANV": "hahaha",
      "C": "${B_ENV}"
    }
  B_ENV: b_env

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ env.TARGET_BRANCH }}' | jq -r 'to_entries[] | "\(.key) \(.value)"' |
          while read -r key value; do
            echo "$key=\$$value" >> "$GITHUB_ENV"
          done
      - run: echo $TEST_ENV
      - run: echo $TEST_ANV
      - run: echo $C
