name: GitHub Actions Demo

on: push

jobs:
  job1:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  
  job2:
    if: always() && needs.job1.result != 'failure'
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "This should not run"
