name: GitHub Actions Demo

on: [push, workflow_dispatch]

jobs:
  build:
    name: Calver release
    runs-on: ubuntu-latest
    steps:
      - name: Calver Release
        uses: StephaneBour/actions-calver@master
        with:
          date_format: "%Y.%m"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
