name: GitHub Actions Demo

on: [push]

env:
  tHis_iS_a_VariAblE: 'haha'

jobs:
  ga-test:
    runs-on: ubuntu-latest
    steps:
      - if: env.THIS_IS_A_VARIABLE == 'haha'
        run: echo "not case sensitive"
      - if: env.tHis_iS_a_VariAblE == 'haha'
        run: echo "case sensitive"
