name: GitHub Actions Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      input: |
        {
          "TEST": "$(echo test)",
          "HAHA": "$(echo haha)"
        }
    steps:
      - run: |
          output="{}"
          echo '${{ env.input }}' | jq -r 'to_entries[] | "\(.key) \(.value)"' |
          while read -r key value; do
            val=$(eval "echo \"$value\"")
            echo "$key"
            echo "$val"
            output=`echo $output | jq --arg key "$key" --arg val "$val" '. + {($key): $val}'`
          done
          echo $output
