name: GitHub Actions Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      one: 'one'
      two: 'two'
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ env.one || env.two }}
