name: GitHub Actions Demo

on: [push, workflow_dispatch]

jobs:
  build:
    name: Input check
    runs-on: ubuntu-latest
    steps:
      - name: Calver Release
        uses: StephaneBour/actions-calver@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
