name: GitHub Actions Demo

on: push

jobs:
  gha-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [{a: "a", b: "b"}, {a: "a"}]
    env:
      TEST: ${{ matrix.test.b == NaN && matrix.test.b || matrix.test.a }}
    steps:
      - run: echo "${TEST}"
