name: GitHub Actions Demo

on: [push]

env:
  tHis_iS_a_VariAblE: 'haha'

jobs:
  gha-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env.tHis_iS_a_VariAblE }}"
      - run: echo "${{ env.THIS_IS_A_VARIABLE }}"
