name: GitHub Actions Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      a: '[]'
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ toJSON(fromJSON(env.a)) == '[]' }}
