name: GitHub Actions Demo

on: 
  push:
    branches:
      - dev

jobs:
  build:
    name: Calver release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: [
          {dir: '.github/actions', account: '164201395711'},
          {dir: 'tf/infra/prd', account: '164201395711'}
        ]
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.dir }}
    steps:
      - run: |
          echo "${{ matrix.dir }}" "${{ matrix.account }}"
          pwd
