name: GitHub Actions Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      command: |
        echo "command 1"
        echo "command 2"
    steps:
      - run: |
          echo "tes"
          ${{ env.command }}
