name: GitHub Actions Demo

on:
  push

env:
  TAG_NAME: ${{ github.ref_name }}

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
    - run: |
        HAHA=`echo "haha"`
        echo "$HAHA"

