name: GitHub Actions Demo

on: push

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Calver Release
        uses: StephaneBour/actions-calver@master
        with:
          date_format: "%Y.%-m"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

