name: GitHub Actions Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "HAHA=" >> "$GITHUB_ENV"
          echo "HEHE=hehe" >> "$GITHUB_ENV"
      - run: |
          echo $HAHA
          echo $HEHE
