name: GitHub Actions Demo

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Calver release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Calver Release
        uses: HENNGE/actions-calver@master
        with:
          date_format: "%Y.%m"
          release_branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
