name: GitHub Actions Demo

on: push

jobs:
  gha-test:
    runs-on: ubuntu-latest
    steps:
      - run: pip freeze
        shell: bash
      - uses: FurqanHabibi/gha-test@v1
      - run: pip freeze
        shell: bash
