name: GitHub Actions Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "HAHA=haha" >> "$GITHUB_ENV"
          echo "HEHE=" >> "$GITHUB_ENV"
          echo "HUHU=huhu" >> "$GITHUB_ENV"
      - run: |
          echo $HAHA
          echo $HEHE
          echo $HUHU
