name: GitHub Actions Demo

on: push

jobs:
  check-date-each:
    runs-on: ubuntu-latest
    steps:
      - run: date # Fri Jan 14 16:30:55 UTC 2022
      - run: date # Sat Jan 15 01:30:55 JST 2022
        env:
          TZ: 'Asia/Tokyo'

