name: GitHub Actions Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [one, two]
        exclude:
          - a: one
          - a: two
    steps:
      - uses: actions/checkout@v3
      - run: echo "HAHAHA ${{ matrix.a }}"
