name: GitHub Actions Demo

on: push

env:
  SECRETS: ${{ toJSON(secrets) }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ env.SECRETS }}' | jq -r 'to_entries[] | "\(.key) \(.value)"' |
          while read -r key value; do
            val=$(eval "echo \"$value\"")
            echo "$key=$val" >> "$GITHUB_ENV"
          done
      - run: echo "$github_token"
      - run: echo "$TEST"
      - run: echo "${TEST_LAGI}haha"

