name: GitHub Actions Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      TF_CUR_DIR: './tf/infra/prd'
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: errored-tfstate_${{ env.TF_CUR_DIR }}
          path: ${{ env.TF_CUR_DIR }}/errored.tfstate
